bump up max_result_size
avoid:
py4j.protocol.Py4JJavaError: An error occurred while calling o171.jdbc.
: org.apache.spark.SparkException: Job aborted due to stage failure:
Total size of serialized results of 69303 tasks (1024.0 MB) is bigger than spark.driver.maxResultSize (1024.0 MB)